"""fix_ml_models_columns

Revision ID: 67aa6d1f8081
Revises: f77c0139da81
Create Date: 2026-05-12 11:41:53.959549
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '67aa6d1f8081'
down_revision: Union[str, None] = 'f77c0139da81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic autogenerate missed these because the table already existed.
    # Manually adding missing columns to ml_models.
    op.execute("ALTER TABLE ml_models ADD COLUMN IF NOT EXISTS model_type VARCHAR(50)")
    op.execute("ALTER TABLE ml_models ADD COLUMN IF NOT EXISTS version VARCHAR(20)")
    op.execute("ALTER TABLE ml_models ADD COLUMN IF NOT EXISTS trained_at TIMESTAMPTZ")
    op.execute("ALTER TABLE ml_models ADD COLUMN IF NOT EXISTS rmse FLOAT")
    op.execute("ALTER TABLE ml_models ADD COLUMN IF NOT EXISTS mae FLOAT")
    op.execute("ALTER TABLE ml_models ADD COLUMN IF NOT EXISTS artifact_path VARCHAR(200)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
