"""initial_schema

Revision ID: f7355e36e42f
Revises: 
Create Date: 2026-04-23 11:41:33.994114
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f7355e36e42f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('track_length_km', sa.Float(), nullable=True),
    sa.Column('lap_record_s', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constructors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('drivers',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=60), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('artifact_path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('championship_standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('after_round', sa.Integer(), nullable=False),
    sa.Column('driver_code', sa.String(length=3), nullable=False),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_code'], ['drivers.code'], ),
    sa.ForeignKeyConstraint(['season_year'], ['seasons.year'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_season',
    sa.Column('driver_code', sa.String(length=3), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=True),
    sa.Column('car_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_code'], ['drivers.code'], ),
    sa.ForeignKeyConstraint(['season_year'], ['seasons.year'], ),
    sa.PrimaryKeyConstraint('driver_code', 'season_year')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('race_date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['season_year'], ['seasons.year'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_year', 'round_number', name='uq_round_season_number')
    )
    op.create_table('laps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('driver_code', sa.String(length=3), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('lap_time_s', sa.Float(), nullable=True),
    sa.Column('sector1_s', sa.Float(), nullable=True),
    sa.Column('sector2_s', sa.Float(), nullable=True),
    sa.Column('sector3_s', sa.Float(), nullable=True),
    sa.Column('compound', sa.String(length=10), nullable=True),
    sa.Column('tyre_life', sa.Integer(), nullable=True),
    sa.Column('stint', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('track_status', sa.String(length=5), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_code'], ['drivers.code'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_laps_driver_compound', 'laps', ['driver_code', 'compound'], unique=False)
    op.create_index('ix_laps_round_driver', 'laps', ['round_id', 'driver_code'], unique=False)
    op.create_table('qualifying',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('driver_code', sa.String(length=3), nullable=False),
    sa.Column('q1_s', sa.Float(), nullable=True),
    sa.Column('q2_s', sa.Float(), nullable=True),
    sa.Column('q3_s', sa.Float(), nullable=True),
    sa.Column('grid_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_code'], ['drivers.code'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('driver_code', sa.String(length=3), nullable=False),
    sa.Column('finish_position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('fastest_lap', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_code'], ['drivers.code'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_results')
    op.drop_table('qualifying')
    op.drop_index('ix_laps_round_driver', table_name='laps')
    op.drop_index('ix_laps_driver_compound', table_name='laps')
    op.drop_table('laps')
    op.drop_table('rounds')
    op.drop_table('driver_season')
    op.drop_table('championship_standings')
    op.drop_table('seasons')
    op.drop_table('ml_models')
    op.drop_table('drivers')
    op.drop_table('constructors')
    op.drop_table('circuits')
    # ### end Alembic commands ###
