"""fix_compound_length_and_mlmodel_schema

Revision ID: f77c0139da81
Revises: f7355e36e42f
Create Date: 2026-04-24 14:29:57.407151
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f77c0139da81'
down_revision: Union[str, None] = 'f7355e36e42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laps', 'compound',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.add_column('ml_models', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('ml_models', sa.Column('metrics', sa.JSON(), nullable=True))
    op.add_column('ml_models', sa.Column('feature_names', sa.JSON(), nullable=True))
    op.add_column('ml_models', sa.Column('hyperparams', sa.JSON(), nullable=True))
    op.alter_column('ml_models', 'artifact_path',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.create_unique_constraint(None, 'ml_models', ['name'])
    op.drop_column('ml_models', 'model_type')
    op.drop_column('ml_models', 'mae')
    op.drop_column('ml_models', 'rmse')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_models', sa.Column('rmse', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ml_models', sa.Column('mae', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ml_models', sa.Column('model_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ml_models', type_='unique')
    op.alter_column('ml_models', 'artifact_path',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('ml_models', 'hyperparams')
    op.drop_column('ml_models', 'feature_names')
    op.drop_column('ml_models', 'metrics')
    op.drop_column('ml_models', 'name')
    op.alter_column('laps', 'compound',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
