[theme]
primaryColor="#E10600"
backgroundColor="#000000"
secondaryBackgroundColor="#0A0A0A"
textColor="#FFFFFF"
font="sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false
